apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickit-app
  labels:
    app: tickit-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tickit-app
  template:
    metadata:
      labels:
        app: tickit-app
    spec:
      containers:
      - name: tickit-app
        image: mayur702/tickit-app:latest
        ports:
        - containerPort: 8000
